#!/usr/bin/env bash
#loop to print "best school" with condition(Hi)

i=0
while [ $i -lt 10 ]
do
        if [ $i -eq 9 ]
        then
                echo -e "Hi"
        fi
        echo "Best School"
        i=$(( i + 1 ))
done
