#!/usr/bin/env bash
#loop to print "best school" with condition(Hi)

i=1
while [ $i -lt 10 ]
do
        if [ $i -eq 4 ]
        then
                echo "bad luck"

	elif [ $i -eq 8 ]
	then 
		echo "good luck"

	else
	then
		echo "Best School"
	fi

        (( i++ ))
done
