#!/usr/bin/env bash
#clock program

hour=0
min=1

while [ $hour -le 12 ]
do
        echo "Hour: $hour"
        min=1
        while [ $min -lt 60 ]
        do
                echo "$min"
                (( min++ ))
        done

        (( hour++ ))
done
