#!/usr/bin/env bash
#checking if there is a file or not

(( file="school" ))

if [ -e $file ]
then
	echo "$file file exists"

else
	echo "$file file does not exist"
fi

if [ -s $file ]
then
	echo "$file file is empty"

else 
	echo "$file is not empty"
fi

if [ -f $file ]
then
	echo "$file file is a regular file"

fi
