#!/usr/bin/env bash
#manage my process

case "$1" in

	start)
		start manage_my_process &
		ps > /var/run/my_process.pid 
		echo "manage_my_process started" 
		;;

	stop)
		stop manage_my_process 
		rm /var/run/my_process.pid 
		echo "manage_my_process stopped" 
		;;

	restart)
		
		stop manage_my_process 
		rm /var/run/my_process.pid 
		start manage_my_process &
		ps > /var/run/my_process.pid
		echo "manage_my_process restarted" 

	*)	
		echo "Usage: manage_my_process {start|stop|restart}" 
		


