#!/usr/bin/env bash
#manage my process

file=cat /var/run/my_process.pid)

case "$1" in

	start)
		./manage_my_process &
		echo $$ > /var/run/my_process.pid 
		echo "manage_my_process started" 
		;;

	stop)
		kill -15 $$($file)
		rm -f | sudo tee -a /var/run/my_process.pid
		echo "manage_my_process stopped" 
		;;

	restart)
		
		kill -15 $$($file)
		rm -f | sudo tee -a /var/run/my_process.pid
		./manage_my_process &
		echo $$ > /var/run/my_process.pid
		echo "manage_my_process restarted"
		;;

	*)	
		echo "Usage: manage_my_process {start|stop|restart}" 
		
	esac


